# Generated by Django 5.1.6 on 2025-04-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='dropoff_latitude',
            new_name='drop_latitude',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='dropoff_longitude',
            new_name='drop_longitude',
        ),
        migrations.AddField(
            model_name='driver',
            name='car_type',
            field=models.CharField(default='Sedan', max_length=50),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancellation_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='car_type',
            field=models.CharField(default='Sedan', max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
