# Generated by Django 5.1.6 on 2025-04-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rename_available_driver_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('Driver delayed', 'Driver delayed'), ('Change of plans', 'Change of plans'), ('Found another ride', 'Found another ride')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
