# Generated by Django 5.1.6 on 2025-04-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_cancellation_reason_ride_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='fare',
            field=models.FloatField(default=0.0),
        ),
    ]
