# Generated by Django 5.1.6 on 2025-04-21 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_ride_car_type_remove_ride_estimated_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='estimated_time_minutes',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='preferred_car_type',
        ),
        migrations.AddField(
            model_name='ride',
            name='car_type',
            field=models.CharField(default='Sedan', max_length=50),
        ),
        migrations.AddField(
            model_name='ride',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_type',
            field=models.CharField(default='Sedan', max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='cancellation_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('Driver delayed', 'Driver delayed'), ('Change of plans', 'Change of plans'), ('Found another ride', 'Found another ride')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.driver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='fare',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
