# Generated by Django 5.1.6 on 2025-04-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_alter_driver_latitude_alter_driver_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='cancellation_fee',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='estimated_time',
        ),
    ]
