# Generated by Django 5.1.6 on 2025-04-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_remove_driver_phone_number_remove_ride_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
