# Generated by Django 5.1.6 on 2025-04-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_remove_ride_cancellation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cancellation_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
