# Generated by Django 5.1.6 on 2025-04-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ride_cancellation_fee_ride_estimated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='estimated_time',
        ),
    ]
