# Generated by Django 4.2.7 on 2025-05-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_alter_ride_cancellation_fee_alter_ride_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='registration_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('Pickup location far away', 'Pickup location far away'), ('Change of plans', 'Change of plans'), ('Found another ride', 'Found another ride')], max_length=50, null=True),
        ),
    ]
