# Generated by Django 5.1.6 on 2025-04-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_remove_ride_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
