# Generated by Django 4.2.7 on 2025-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_driver_car_model_driver_car_plate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
